### ISSUE TITLE
what to enter here

### ISSUE THREAD

**Issue by Pe0xonN** [tgdrive/teldrive-ui#4]
![image](https://github.com/divyam234/teldrive-ui/assets/142345756/cae5b9f8-62ab-4dba-b809-9e593037894d)

**Comment by Pe0xonN** [comment]
![image](https://github.com/divyam234/teldrive-ui/assets/142345756/19faa26e-4d5c-4cad-850d-a431ec20f9da)

**Comment by joseavilasg** [comment]
Hi @Pe0xonN! To get started, make sure to input the API URL. You can clone [this repo](https://github.com/divyam234/teldrive), build the Go project for your operating system, or use the Docker image, and it will run on port 8080. The API URL should be set as http://localhost:8080/. You can find the complete process outlined in the [README file](https://github.com/divyam234/teldrive/blob/main/README.md).

**Comment by Pe0xonN** [comment]
@joseavilasg09 Can you explain how I should do this on Windows?

**Comment by Pe0xonN** [comment]
@joseavilasg09 Or somehow remotely without windows
